### ISSUE TITLE
VPC Provisioning - Actual Networking

### ISSUE THREAD

**Issue by Kahuna915** [Kahuna915/Capstone-Design#10]
- [] Site to site VPN/DNS/etc. 
- [] Setting up for different regions (aka Ireland Campus)
- [] Fileshare with AWS?
- [] Subnet planning (Joyce, Skiff, Foster)

**Comment by TannerWeinacker** [comment]
What is cyber.local using?
What are the virtual machines using?
What will AWS use?
IP addresses and subnetting?
Students and faculty subnets?
